### ISSUE TITLE
news about the project

### ISSUE THREAD

**Issue by lduboeuf** [ycheng/mir-vnc-server#1]
hello,

Just to know, even if old project, does your vncserver used to work ?
The api as changed a little since, would love to see my Ubuntu Touch device on my Desktop through VNC :)

**Comment by ycheng** [comment]
Yes, it used to.

**Comment by lduboeuf** [comment]
ok, well i don't have the skill yet to get it working. I successfully compiled though, can see only a frozen screenshot without any possible interaction. The api have changed and a known bug will not be fixed for Ubuntu Touch  on 15.04. i will have a try whenever 16.04 is ready. If you plan to share your success story to the [UBPorts community](https://www.ubports.com/), would be great :)
